const SELECT_COURSE = 'SELECT_COURSE';

const UNSELECT_COURSE = 'UNSELECT_COURSE';

const FETCH_COURSE_SUCCESS = 'FETCH_COURSE_SUCCESS';

module.exports = {
  SELECT_COURSE,
  UNSELECT_COURSE,
  FETCH_COURSE_SUCCESS,
};
